services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysql
      #- SPRING_DATASOURCE_USERNAME=root
      #- SPRING_DATASOURCE_PASSWORD=mysql

    ports:
      - "8080:9090"

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db1
      MYSQL_USER: shankar
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql

    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /var/lib/mysql